name: Go

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: ['1.20']
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - name: Configure git for private relab repo
      env:
        TOKEN: ${{ secrets.CT_SECRET }}
      run: git config --global url."https://relab-robot:${TOKEN}@github.com".insteadOf "ssh://git@github.com"
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}
    - name: Set git to use LF
      # make sure that line endings are not converted on windows
      run: git config --global core.autocrlf false
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.OS }}-build-${{ env.cache-name }}-
          ${{ runner.OS }}-build-
          ${{ runner.OS }}-
    - name: Setup protoc
      uses: arduino/setup-protoc@v1.1.2
    - name: Install tools
      run: make tools
    - name: Build Source
      run: make build
    - name: Make cli
      run: make bench
    - name: Vet
      run: make vet
    - name: Test with Race Detector
      run: make racetest
