name: Go

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    env:
      GOPRIVATE: "github.com/relab/ct-eth"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: [1.16]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - name: Set git to use LF
      # make sure that line endings are not converted on windows
      run: git config --global core.autocrlf false
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Cache Go modules
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.OS }}-build-${{ env.cache-name }}-
          ${{ runner.OS }}-build-
          ${{ runner.OS }}-
    - name: Build Contracts
      run: make contracts
    - name: Build Source
      run: make build
    #TODO: Remove bench from the default build.
    - name: Make binary benchmark
      run: make binary
    - name: Lint
      run: make lint
    - name: Vet
      run: make vet
    - name: Test with Race Detector
      run: make racetest
